cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:movie_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:movie_id>/', views.cart_remove, name='cart_remove'),

]

moviespot/urls.py
from django.contrib import admin
from django.urls import path, include

from mspot.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('zamowienia/', include('zamowienia.urls', namespace='zamowienia')),
    path('accounts/', include('django.contrib.auth.urls')), #new
    path("register/", register, name="register"),


    path('', include('mspot.urls', namespace='mspot')),
]

mspot/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'mspot'
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<slug:category_slug>/', views.movie_list, name='movie_list_by_gatunek'),
    path('<int:id>/<slug:slug>/', views.movie_detail, name='movie_detail'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zamowienia/urls.py
from django.urls import path
from. import views

app_name = 'zamowienia'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

MOVIE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddMovieForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=MOVIE_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mspot.models import Movie
from .cart import Cart
from .forms import CartAddMovieForm


@require_POST
def cart_add(request, movie_id):
    cart = Cart(request)
    movie = get_object_or_404(Movie, id=movie_id)
    form = CartAddMovieForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(movie=movie,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, movie_id):
    cart = Cart(request)
    movie = get_object_or_404(Movie, id=movie_id)
    cart.remove(movie)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddMovieForm(initial={'quantity': item['quantity'],
                                                                 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Koszyk na zakupy
{% endblock %}

{% block content %}
  <h1>Koszyk na zakupy</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Zdjęcie</th>
        <th>Produkt</th>
        <th>Ilość</th>
        <th>Usuń</th>
        <th>Cena jednostkowa</th>
        <th>Cena</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with movie=item.movie %}
          <tr>
            <td>
              <a href="{{ movie.get_absolute_url }}">
                <img src="{{ movie.movie_poster.url }}" alt="{{ movie.name }}">
              </a>
            </td>
            <td>{{ movie.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" movie.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Uaktualnij">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" movie.id %}" method="post">
                <input type="submit" value="Usuń">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">{{ item.price }} zł</td>
            <td class="num">{{ item.total_price }} zł</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Razem</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} zł</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "mspot:movie_list" %}" class="button
    light">Kontynuuj zakupy</a>
    <a href="{% url "zamowienia:order_create" %}" class="button">
      Złóż zamowienie
    </a>
  </p>
{% endblock %}